name: Build ABLER/main

on:
  push:
    branches:
      - ABLER/main
  pull_request:
    branches:
      - ABLER/main
  # allow manual dispatches
  workflow_dispatch:

jobs:
  builder:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        builder: ["windows"]
        include:
          - builder: "windows"
            os: "windows-2019"
    steps:
      - name: Cache lib folder
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/lib
          key: ${{ matrix.builder }}-lib-${{ github.ref }}-${{ runner.OS }}
          restore-keys: |
            ${{ matrix.builder }}-lib-${{ github.ref }}
            ${{ matrix.builder }}-lib

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

#      - name: worker_preparation
#        run: mkdir -p ${{ github.workspace }}/build

      - name: Checkout Blender ${{ matrix.branch }}
        uses: actions/checkout@v2
        with:
          path: blender.git
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GIT_KEY }}

      - name: submodules and libraries update
        working-directory: ${{ github.workspace }}/build_windows_x64_vc17_Release
        run: python ../blender.git/build_files/buildbot/worker_update.py ${{ matrix.builder }} ${{ matrix.branch }}

      - name: compile
        working-directory: ${{ github.workspace }}/build_windows_x64_vc17_Release
        run: python ../blender.git/build_files/buildbot/worker_compile.py ${{ matrix.builder }} ${{ matrix.branch }}

#      - name: test
#        working-directory: ${{ github.workspace }}/build_windows_x64_vc17_Release
#        run: python ../blender.git/build_files/buildbot/worker_test.py ${{ matrix.builder }} ${{ matrix.branch }}
#
#      - name: package
#        working-directory: ${{ github.workspace }}/build_windows_x64_vc17_Release
#        run: python ../blender.git/build_files/buildbot/worker_pack.py ${{ matrix.builder }} ${{ matrix.branch }}
      - name: Compress folder
        working-directory: ${{ github.workspace }}/build_windows_x64_vc17_Release/bin/Release
        run: Compress-Archive . ../../../Release.zip

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: abler-${{ matrix.builder }}
          path: ${{ github.workspace }}/Release.zip

      - name: Delete archive
        working-directory: ${{ github.workspace }}
        run: Remove-Item -Path Release.zip

